server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/prjdb?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123
  mvc:
    date-format: yyyy-MM-dd
    static-path-pattern: /**
    resources:
      static-locations: classpath:/static/
  jackson:
    date-format: yyyy-MM-dd
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
